SAMPLING_RATE: 0.20
INITIAL_SLEEP: 5
MAX_AGE: 2                # used in IOUTracker
IOU_THRESHOLD: 0.25       # used in IOUTracker
CONF_THRESHOLD: 0.5       # used in FrameProcessing
INTERVAL_RESULT_LIMIT: 10 # used in VideoProcessing